title: Peixuan Yu's Homepage
page-top-title: Peixuan Yu
top-section-bg-text: HIT&ensp;计算学部&ensp;2025级硕士研究生
home-subtitle: Peixuan Yu&ensp;|&ensp;于沛萱
copyright-text: '&copy; Peixuan Yu 2025. All Rights Reserved.'
